# Generated by Django 3.0.3 on 2020-04-10 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_auto_20200410_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='input',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='output',
        ),
    ]
