# Generated by Django 3.0.3 on 2020-04-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_auto_20200410_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='local',
            field=models.BooleanField(default=False),
        ),
    ]
