# Generated by Django 3.0.3 on 2020-08-09 20:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=30)),
                ('zip_code', models.TextField(max_length=10)),
                ('title', models.TextField(max_length=30)),
                ('description', models.TextField(max_length=30)),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip', models.TextField(default='', max_length=5)),
                ('address', models.TextField(default='', max_length=30)),
                ('longitude', models.FloatField(blank=True, default=None, null=True)),
                ('latitude', models.FloatField(blank=True, default=None, null=True)),
                ('location_img', models.ImageField(blank=True, upload_to='images/')),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='rocker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rocker_yet', models.BooleanField(default=False)),
                ('local', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sport_Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_location_img', models.ImageField(upload_to='images/')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rock.Location')),
                ('rocker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rock.rocker')),
            ],
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.TextField(max_length=30)),
                ('is_basketball', models.BooleanField(default=False)),
                ('is_tennis', models.BooleanField(default=False)),
                ('is_baseball', models.BooleanField(default=False)),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now=True)),
                ('rocker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rock.rocker')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=30)),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('feedback', models.TextField(blank=True, max_length=200)),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now=True)),
                ('destination', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rock.Destination')),
                ('rocker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rock.rocker')),
            ],
            options={
                'unique_together': {('rocker', 'destination')},
            },
        ),
        migrations.AddField(
            model_name='location',
            name='rocker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rock.rocker'),
        ),
        migrations.AddField(
            model_name='location',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rock.Sport'),
        ),
        migrations.AddField(
            model_name='destination',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rock.Location'),
        ),
        migrations.AddField(
            model_name='destination',
            name='rocker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rock.rocker'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=100)),
                ('created', models.DateField(auto_now=True)),
                ('updated', models.DateField(auto_now=True)),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rock.Review')),
                ('rocker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rock.rocker')),
            ],
        ),
    ]
