# Generated by Django 3.0.3 on 2020-08-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location_img',
            new_name='sport_location_img',
        ),
        migrations.AddField(
            model_name='location',
            name='is_baseball',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='is_basketball',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='location',
            name='is_tennis',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='sport',
            field=models.TextField(default='', max_length=30),
        ),
    ]
