# Generated by Django 3.0.3 on 2020-08-07 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_basketball', models.BooleanField(default=False)),
                ('is_tennis', models.BooleanField(default=False)),
                ('is_baseball', models.BooleanField(default=False)),
                ('rocker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rock.rocker')),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rock.Sport'),
        ),
    ]
