# Generated by Django 3.0.3 on 2020-08-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0002_auto_20200807_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='sport',
            name='created',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='sport',
            name='sport',
            field=models.TextField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='sport',
            name='updated',
            field=models.DateField(auto_now=True),
        ),
    ]
