# Generated by Django 3.0.3 on 2020-08-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0002_auto_20200810_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='sport_location_img',
            field=models.ImageField(blank=True, default="{% static 'rock/images/bball.PNG' %}", upload_to='images/'),
        ),
    ]
