# Generated by Django 3.0.3 on 2020-08-07 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0003_auto_20200807_1302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sport',
            name='sport',
            field=models.TextField(max_length=30),
        ),
    ]
