# Generated by Django 3.0.3 on 2020-08-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0005_auto_20200807_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='location',
            name='longitute',
            field=models.FloatField(default=0),
        ),
    ]
