# Generated by Django 3.0.3 on 2020-08-15 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0005_auto_20200813_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='sport_location_img',
            field=models.ImageField(default='static/rock/images/no_image_available.PNG', upload_to='images/'),
        ),
    ]
