# Generated by Django 3.0.3 on 2020-08-08 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0006_auto_20200808_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(default=0, max_length=30),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitute',
            field=models.FloatField(default=0, max_length=30),
        ),
    ]
