# Generated by Django 3.0.3 on 2020-08-08 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0007_auto_20200808_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='longitute',
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
    ]
