# Generated by Django 3.0.3 on 2020-08-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0008_auto_20200808_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=8, null=True),
        ),
    ]
