# Generated by Django 3.0.3 on 2020-08-23 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0008_auto_20200823_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='sport_location_img',
            field=models.FileField(blank=True, default='static/rock/images/no_image_available.PNG', upload_to=''),
        ),
    ]
