# Generated by Django 3.0.3 on 2020-08-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0008_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='img_url',
            field=models.TextField(default='', max_length=100),
        ),
    ]
