# Generated by Django 3.0.3 on 2020-08-24 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0008_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='upload',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rock.Upload'),
        ),
    ]
