# Generated by Django 3.0.3 on 2020-08-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0009_auto_20200820_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='sport_location_img',
            field=models.ImageField(blank=True, default='static/rock/images/no_image_available.PNG', upload_to='findtherock.s3.amazonaws.com/media/'),
        ),
    ]
