# Generated by Django 3.0.3 on 2020-08-08 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0009_auto_20200808_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
    ]
