# Generated by Django 3.0.3 on 2020-08-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0010_auto_20200808_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
