# Generated by Django 3.0.3 on 2020-08-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0011_auto_20200826_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='upload',
        ),
    ]
