# Generated by Django 3.0.3 on 2020-08-09 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0011_auto_20200808_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport_Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_location_img', models.ImageField(upload_to='images/')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rock.Location')),
                ('rocker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rock.rocker')),
            ],
        ),
    ]
