# Generated by Django 3.0.3 on 2020-08-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0013_location_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
