# Generated by Django 3.0.3 on 2020-08-26 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0014_auto_20200826_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='file',
            field=models.FileField(blank=True, default=None, upload_to=''),
        ),
    ]
