# Generated by Django 3.0.3 on 2020-08-26 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rock', '0015_auto_20200826_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='file',
        ),
    ]
